name: ClickUp to CSV Sync

on:
  schedule:
    - cron: '0 * * * *'  # Her saat başı çalışır
  workflow_dispatch:      # Manuel tetikleme

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      CLICKUP_API_TOKEN: ${{ secrets.CLICKUP_API_TOKEN }}
      TEAM_ID: ${{ vars.TEAM_ID }}
      OUTPUT_PATH: ${{ vars.OUTPUT_PATH }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install packs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        run: python CUP2PBI.py

      - name: Upload csv as artifact
        uses: actions/upload-artifact@v4
        with:
          name: clickup_tasks_csv
          path: clickup_tasks_full.csv

      - name: Install Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Setup Rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Upload CSV to OneDrive
        run: |
          rclone copy clickup_tasks_full.csv "onedrive:/PowerBI/" --progress
