name: ClickUp to CSV Sync

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:     

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install packs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Variables
        run: |
          echo "CLICKUP_API_TOKEN=${{ secrets.CLICKUP_API_TOKEN }}" >> $GITHUB_ENV
          echo "TEAM_ID=${{ secrets.TEAM_ID }}" >> $GITHUB_ENV
          echo "OUTPUT_PATH=clickup_tasks_full.csv" >> $GITHUB_ENV

      - name: Run Script
        run: python CUP2PBI.py

      - name: Upload csv
        uses: actions/upload-artifact@v4
        with:
          name: clickup_tasks_csv
          path: clickup_tasks_full.csv
